#ifndef FILM_HPP
#define FILM_HPP

#include <cstdint>
#include <vector>

#include "common.hpp"
#include "geometry.hpp"
#include "paramset.hpp"

namespace ryt {

using byte = std::uint8_t;

// ==============================================================================
// Film Class
// ==============================================================================

/*!
 * Represents an image generated by the ray tracer.
 * It holds the pixel data, image dimensions, and format configuration,
 * as well as the logic to export the final result to the disk.
 */
class Film {
public:
  /// List of supported image file formats.
  enum class image_type_e : byte { PNG = 0, PPM3, PPM6 };

  // ==============================================================================
  // Film Public Methods
  // ==============================================================================

  /// Constructs a Film with specified resolution, output path, format, and gamma correction.
  Film(const Point2i& resolution,
       const std::string& filename,
       image_type_e image_type,
       bool gamma_corrected);
  virtual ~Film();

  /// Retrieves the original film resolution.
  [[nodiscard]] Point2i get_resolution() const { return m_full_resolution; };

  /// Takes a sample `pixel_coord` and its radiance `pixel_color` and updates the image.
  void add_sample(const Point2i&, const RGBColor&);

  /// Writes the accumulated image data to a file on disk.
  void write_image() const;

  // ==============================================================================
  // Film Public Data
  // ==============================================================================

  const Point2i m_full_resolution;  //!< The image's full resolution values.
  // Bounds2i m_crop_pix_bounds;    //!< Crop window in pixel (raster) coordinates.
  std::string m_filename;           //!< Full path file name + extension.
  bool m_activate_gamma_correction; //!< Gamma correction flag, requesting the correction if on.
  image_type_e m_image_type;        //!< Image type, PNG, PPM3, PPM6.

  std::vector<RGBColor> m_pixels;   //!< Linear color buffer storing the image's pixels.
};

// ==============================================================================
// Factory & Helper Functions
// ==============================================================================

/// Factory function to create a new Film object based on parsed attributes.
Film* create_film(const ParamSet& ps);

/// Helper function to resolve the output filename.
std::string handles_filename(const ParamSet& ps);

// ryt::Bounds2f handles_cropwindow(const ParamSet& ps);

/// Helper function to resolve and adjust the film dimensions.
ryt::Point2i handles_dimensions(const ParamSet& ps);

}  // namespace ryt

#endif  // FILM_HPP
